export enum EnvKeyEnum {
  JWTSecretKey = 'JWT_SECRET',
  JWTRefreshSecretKey = 'JWT_REFRESH_SECRET',
  JWTExpiresIn = 'JWT_EXPIRES_IN',
  JWTExpiresInUnit = 'JWT_EXPIRES_IN_UNIT',
  AppUrl = 'APP_URL',
  MaxPayloadSize = 'MAX_PAYLOAD_SIZE',
  SwaggerTitle = 'SWAGGER_TITLE',
  SwaggerDescription = 'SWAGGER_DESCRIPTION',
  SwaggerVersion = 'SWAGGER_VERSION',
  SwaggerUri = 'SWAGGER_URI',
  MaxSlugGenerateAttempts = 'MAX_SLUG_GENERATE_ATTEMPTS',
  MaxUrlLength = 'MAX_URL_LENGTH',
  CryptSecret = 'CRYPT_SECRET',
  EmailMainAddress = 'EMAIL_MAIN_ADDRESS',
  EmailFrom = 'EMAIL_FROM',
  EmailTransport = 'EMAIL_TRANSPORT',
  FrontURL = 'FRONT_URL',
  FrontURLResetPassword = 'FRONT_URL_RESET_PASSWORD',
}
